<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFx7xwer\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFx7xwer/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFx7xwer.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFx7xwer\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFx7xwer\appProdProjectContainer([
    'container.build_hash' => 'Fx7xwer',
    'container.build_id' => '889cff20',
    'container.build_time' => 1609214175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFx7xwer');
